### ISSUE TITLE
QNEthernet corrections, changes, and additions

### ISSUE THREAD

**Issue by ssilverman** [JAndrassy/Arduino-Networking-API#1]
Great work collecting all this information. I have some corrections, changes, and additions for the _QNEthernet_ library. First, I'll note that the library does implement every method defined by the [Arduino Ethernet API reference](https://www.arduino.cc/reference/en/libraries/ethernet/), even if some are no-op's.

1. All the _begin_ functions that accept a MAC address are identical to the Arduino-defined ones. I've added additional ones that don't take a MAC address. This means that there's both a non-blocking `begin()` _and_ a blocking `begin(mac, [timeout])` for starting with DHCP. ([Line 44 in table](https://github.com/JAndrassy/Arduino-Networking-API/blob/73689a607c35a63d9a7a142807a1eecae357cc29/ArduinoNetAPILibs.md?plain=1#L44) and [QNEthernet line](https://github.com/ssilverman/QNEthernet/blob/0737b405bf23dc5d3afc3f72d760d03163ae7854/src/QNEthernet.h#L253))
2. Same table line, the parameter order for the static IP versions are _not_ in the wrong order. You may have been looking at my extra _begin_ functions that aren't defined in the Arduino API. ([QNEthernet lines starting here](https://github.com/ssilverman/QNEthernet/blob/0737b405bf23dc5d3afc3f72d760d03163ae7854/src/QNEthernet.h#L255))
3. There is, in addition to `setDNSServerIP()`, the Arduino API-defined `setDnsServerIP()`. ([Line 79 in table](https://github.com/JAndrassy/Arduino-Networking-API/blob/73689a607c35a63d9a7a142807a1eecae357cc29/ArduinoNetAPILibs.md?plain=1#L79) and [QNEthernet line](https://github.com/ssilverman/QNEthernet/blob/0737b405bf23dc5d3afc3f72d760d03163ae7854/src/QNEthernet.h#L281))
4. The get-host-by-name functionality is in the `DNSClient` class ([Line 165 in table](https://github.com/JAndrassy/Arduino-Networking-API/blob/73689a607c35a63d9a7a142807a1eecae357cc29/ArduinoNetAPILibs.md?plain=1#L165) and [QNEthernet line](https://github.com/ssilverman/QNEthernet/blob/0737b405bf23dc5d3afc3f72d760d03163ae7854/src/QNDNSClient.h#L54) and [QNEthernet README link](https://github.com/ssilverman/QNEthernet#dnsclient))
5. It may not be relevant to the table (same line 165 as previous), but there's a "get time" SNTP example here: https://github.com/ssilverman/QNEthernet/blob/master/examples/SNTPClient/SNTPClient.ino
6. I was wondering how _QNEthernet_'s `connected()` function is "alternative"? It _does_ return `true` if the connection is not connected and there's data. ([Line 182 in table](https://github.com/JAndrassy/Arduino-Networking-API/blob/73689a607c35a63d9a7a142807a1eecae357cc29/ArduinoNetAPILibs.md?plain=1#L182))
7. I actually like the idea of having a client-specific local IP to indicate which network interface the connection is using. :) ([Line 208 in table](https://github.com/JAndrassy/Arduino-Networking-API/blob/73689a607c35a63d9a7a142807a1eecae357cc29/ArduinoNetAPILibs.md?plain=1#L208))

Thanks again for doing all this work!

**Comment by JAndrassy** [comment]
1) 2) 3) updated to ✓
4) 5) that table is about the Ethernet/WiFi object.  other libraries too may have hostByName , time or ping  elsewhere.  
6) `conn_->remaining.empty()`? ✓

**Comment by ssilverman** [comment]
> 1 2 3 updated to ✓
> 4 5 that table is about the Ethernet/WiFi object. other libraries too may have hostByName , time or ping elsewhere.
> 6 `conn_->remaining.empty()`? ✓

For 6, the _QNEthernetClient.cpp_ logic is correct, it only returns false if not connected _and empty_. (I'm not sure if you're disagreeing or agreeing with my point 6. :) )
Thanks for changing the other relevant ones.
